spring:
  application:
    name: data_entry_app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data_entry
    username: root
    password: Yh980604!
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: false
#    mode: HTML
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl